### PR TITLE
an additional task pattern example.

### PR DESCRIPTION
**Pull request by mark-lazarides**
# THIS PR IS FOR DISCUSSIONS
# NOT TO BE MERGED

@PTKu   I was thinking something along these lines. The ideas are really similar, but I prefer to encapsulate the task. This approach has the benefit of lending itself well to the strategy pattern too, without specifying too closely how a task should be implemented. Of course, people could extend this idea with a whole task object pattern as you have done, I just think we should avoid over-engineering the future.

**editted to show just for discussion - thanks @PTKu  for the style guide :-)**

### CODE REVIEW

**Comment by mark-lazarides** [comment]
The Cylinder block has been extended in this example to use two, T_MoveCylinderToPosition classes, implementing an ITaskStatus.
Look at the difference in the tests to see how the block can be used two ways:

- `FB_CylinderTest` Classic OO way - method calls requesting state change, monitoring properties for status
- `FB_CylinderTaskTest` Returning a task interface to monitor the requested task.

**Comment by PTKu** [comment]
@mark-lazarides the solutions are indeed very similar, we can have alternatives, each solution has pros and cons. We can unify interface (ITaskStatus, ITask) to have the same semantics/syntax when consuming the component.

This is a general remark: as for strategy pattern I am not sure how useful it is for us especially when we build components against specific hardware. It may have utility for generic components, but frankly most of the times I used this pattern, I later regretted.  

I do agree that we should not overengineer, what we should focus on, though, is ease of use for the consumers of components (as much declarative and as little imperative possible).

For the others the solutions we are discussing here are this PR and [this](https://github.com/TcOpenGroup/TcOpen) repo's ```dev``` branch.

**Comment by mark-lazarides** [comment]
I have used strategy to really good effect over the last five years, in situations where either functionality needed to be swapped out (different homing routines, alternate start-up patterns, changing interlock logic), and also where a single block provides the necessary abstractions to be universally useful, but the hardware and complexity lower down changes. 

The example in this PR is useful. If the cylinder were extended to accept different strategies for to home and to work, additional IO could be defined in new strategies, but the original cylinder could be reused. Perhaps an interlock is added to a later cylinder. An alternate strategy holding a reference to that can be developed and swapped out. The cylinder doesn't change, but it's strategy for getting to work or to home does.

**Comment by mark-lazarides** [comment]
> @mark-lazarides the solutions are indeed very similar, we can have alternatives, each solution has pros and cons. We can unify interface (ITaskStatus, ITask) to have the same semantics/syntax when consuming the component.

This is also a really good idea, @PTKu. ITask can extend ITaskStatus so people can take from it what they like. I was thinking about that last night - would we allow people to queue up a task in that manner, and get an ITask to start when they want? And if we did, how does that work from a concurrency perspective? I guess we'd want to block any new attempts at queueing up that task, unless it is backed by a work queue (I;m thinking where things need access to a comms bus, for example, they could grab a reference to a comms slot, work on it, then action it and follow it through using the interface).

**Comment by chris-k84** [comment]
you got strategy pattern in there then :-) so what we are saying here then is a class contains a set of strategies that each conform to and use the ITaskStatus, you can call cyclically if you like or use the task methods to get a ref to the task interface back. like the idea of returning the interface like that, also the passing by ref. we could extend that for motion to pass all sorts of commands. i guess the real difference here is you are designing an operation and building the async operation into it, while the fbTask is a stand alone block that 'tracks' if that's the right word the status of an operation. i guess this one imposes a pattern of construction, while the other a pattern of implementation, is that fair to say?

**Comment by mark-lazarides** [comment]
> i guess the real difference here is you are designing an operation and building the async operation into it, while the fbTask is a stand alone block that 'tracks' if that's the right word the status of an operation. i guess this one imposes a pattern of construction, while the other a pattern of implementation, is that fair to say?

I think the two blocks are complimentary, its just the actual way of using them I wasn't so sure about. For examlple I could have extended the fbTask block @PTKu wrote (with some changes as discussed in the comments on #11 ) for the strategies presented here. The key difference I would make would be the fbTask block would be internal to the thing using it, and an interface to it, or the block itself returned.

**Pull request closed without merging**
